/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'apps-activity-logs': RouteRecordInfo<'apps-activity-logs', '/apps/activity-logs', Record<never, never>, Record<never, never>>,
    'apps-area': RouteRecordInfo<'apps-area', '/apps/area', Record<never, never>, Record<never, never>>,
    'apps-content': RouteRecordInfo<'apps-content', '/apps/content', Record<never, never>, Record<never, never>>,
    'apps-operations-material-requests': RouteRecordInfo<'apps-operations-material-requests', '/apps/operations/material-requests', Record<never, never>, Record<never, never>>,
    'apps-operations-materials': RouteRecordInfo<'apps-operations-materials', '/apps/operations/materials', Record<never, never>, Record<never, never>>,
    'apps-operations-pickups': RouteRecordInfo<'apps-operations-pickups', '/apps/operations/pickups', Record<never, never>, Record<never, never>>,
    'apps-operations-visits': RouteRecordInfo<'apps-operations-visits', '/apps/operations/visits', Record<never, never>, Record<never, never>>,
    'apps-orders': RouteRecordInfo<'apps-orders', '/apps/orders', Record<never, never>, Record<never, never>>,
    'apps-orders-approval-requests': RouteRecordInfo<'apps-orders-approval-requests', '/apps/orders/approval-requests', Record<never, never>, Record<never, never>>,
    'apps-orders-bulk-delivery-labels': RouteRecordInfo<'apps-orders-bulk-delivery-labels', '/apps/orders/bulk-delivery-labels', Record<never, never>, Record<never, never>>,
    'apps-orders-bulk-fatora': RouteRecordInfo<'apps-orders-bulk-fatora', '/apps/orders/bulk-fatora', Record<never, never>, Record<never, never>>,
    'apps-orders-bulk-invoice': RouteRecordInfo<'apps-orders-bulk-invoice', '/apps/orders/bulk-invoice', Record<never, never>, Record<never, never>>,
    'apps-orders-bulk-print': RouteRecordInfo<'apps-orders-bulk-print', '/apps/orders/bulk-print', Record<never, never>, Record<never, never>>,
    'apps-orders-client-returns': RouteRecordInfo<'apps-orders-client-returns', '/apps/orders/client-returns', Record<never, never>, Record<never, never>>,
    'apps-orders-client-settlements': RouteRecordInfo<'apps-orders-client-settlements', '/apps/orders/client-settlements', Record<never, never>, Record<never, never>>,
    'apps-orders-client-settlements-id': RouteRecordInfo<'apps-orders-client-settlements-id', '/apps/orders/client-settlements/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-orders-deleted': RouteRecordInfo<'apps-orders-deleted', '/apps/orders/deleted', Record<never, never>, Record<never, never>>,
    'apps-orders-hold-outfordelivery': RouteRecordInfo<'apps-orders-hold-outfordelivery', '/apps/orders/hold-outfordelivery', Record<never, never>, Record<never, never>>,
    'apps-orders-invoice-id': RouteRecordInfo<'apps-orders-invoice-id', '/apps/orders/invoice/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-orders-print-id': RouteRecordInfo<'apps-orders-print-id', '/apps/orders/print/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-orders-rejected': RouteRecordInfo<'apps-orders-rejected', '/apps/orders/rejected', Record<never, never>, Record<never, never>>,
    'apps-orders-scan': RouteRecordInfo<'apps-orders-scan', '/apps/orders/scan', Record<never, never>, Record<never, never>>,
    'apps-orders-shipper-collections': RouteRecordInfo<'apps-orders-shipper-collections', '/apps/orders/shipper-collections', Record<never, never>, Record<never, never>>,
    'apps-orders-shipper-collections-id': RouteRecordInfo<'apps-orders-shipper-collections-id', '/apps/orders/shipper-collections/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-orders-shipper-returns': RouteRecordInfo<'apps-orders-shipper-returns', '/apps/orders/shipper-returns', Record<never, never>, Record<never, never>>,
    'apps-orders-shipping-label-id': RouteRecordInfo<'apps-orders-shipping-label-id', '/apps/orders/shipping-label/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-orders-small-shipping-label-id': RouteRecordInfo<'apps-orders-small-shipping-label-id', '/apps/orders/small-shipping-label/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-orders-tracking-report-id': RouteRecordInfo<'apps-orders-tracking-report-id', '/apps/orders/tracking-report/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-orders-uncollectedclient': RouteRecordInfo<'apps-orders-uncollectedclient', '/apps/orders/uncollectedclient', Record<never, never>, Record<never, never>>,
    'apps-orders-uncollectedshipper': RouteRecordInfo<'apps-orders-uncollectedshipper', '/apps/orders/uncollectedshipper', Record<never, never>, Record<never, never>>,
    'apps-orders-unreturnclient': RouteRecordInfo<'apps-orders-unreturnclient', '/apps/orders/unreturnclient', Record<never, never>, Record<never, never>>,
    'apps-orders-unreturnshipper': RouteRecordInfo<'apps-orders-unreturnshipper', '/apps/orders/unreturnshipper', Record<never, never>, Record<never, never>>,
    'apps-plan': RouteRecordInfo<'apps-plan', '/apps/plan', Record<never, never>, Record<never, never>>,
    'apps-refused-reason': RouteRecordInfo<'apps-refused-reason', '/apps/refused-reason', Record<never, never>, Record<never, never>>,
    'apps-roles': RouteRecordInfo<'apps-roles', '/apps/roles', Record<never, never>, Record<never, never>>,
    'apps-settings': RouteRecordInfo<'apps-settings', '/apps/settings', Record<never, never>, Record<never, never>>,
    'apps-user-clients': RouteRecordInfo<'apps-user-clients', '/apps/user/clients', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-shippers': RouteRecordInfo<'apps-user-shippers', '/apps/user/shippers', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboards-orders': RouteRecordInfo<'dashboards-orders', '/dashboards/orders', Record<never, never>, Record<never, never>>,
    'expense-categories': RouteRecordInfo<'expense-categories', '/expense-categories', Record<never, never>, Record<never, never>>,
    'expenses': RouteRecordInfo<'expenses', '/expenses', Record<never, never>, Record<never, never>>,
    'front-pages-landing-page': RouteRecordInfo<'front-pages-landing-page', '/front-pages/landing-page', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v1': RouteRecordInfo<'pages-authentication-login-v1', '/pages/authentication/login-v1', Record<never, never>, Record<never, never>>,
    'pages-misc-coming-soon': RouteRecordInfo<'pages-misc-coming-soon', '/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'pages-misc-under-maintenance': RouteRecordInfo<'pages-misc-under-maintenance', '/pages/misc/under-maintenance', Record<never, never>, Record<never, never>>,
  }
}
