<?php

use App\Http\Controllers\Api\AclMatrixController;
use App\Http\Controllers\Api\Area\GovernorateController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\Expense\ExpenseCategoryController;
use App\Http\Controllers\Api\Expense\ExpenseController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\Operations\MaterialController;
use App\Http\Controllers\Api\Operations\MaterialRequestController;
use App\Http\Controllers\Api\Operations\MaterialRequestItemController;
use App\Http\Controllers\Api\Operations\PickupRequestController;
use App\Http\Controllers\Api\Operations\VisitController;
use App\Http\Controllers\Api\ActivityLogController;
use App\Http\Controllers\Api\Orders\ClientReturnController;
use App\Http\Controllers\Api\Orders\ClientSettlementController;
use App\Http\Controllers\Api\Dashboard\DashboardOrderController;
use App\Http\Controllers\Api\Orders\OrderController;
use App\Http\Controllers\Api\Orders\ShipperCollectionController;
use App\Http\Controllers\Api\Orders\ShipperReturnController;
use App\Http\Controllers\Api\PermissionController;
use App\Http\Controllers\Api\Plan\PlanController;
use App\Http\Controllers\Api\RefusedReasonController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\WhatsAppController;
use App\Http\Controllers\Api\ShippingContent\ContentController;
use App\Http\Controllers\Api\Users\ClientController;
use App\Http\Controllers\Api\Users\ProfileController;
use App\Http\Controllers\Api\Users\ShipperController;
use App\Http\Controllers\Api\Users\UserController;
use App\Http\Controllers\Api\Public\LandingPageController;
use App\Http\Controllers\Api\Orders\ShipperAppController;
use App\Http\Middleware\UpdateLoginSessionLastSeen;
use Illuminate\Support\Facades\Route;

// Public routes
Route::post('/login', [AuthController::class, 'login']);
Route::get('/landing-page', [LandingPageController::class, 'index']);
Route::get('/orders/track/{code}', [LandingPageController::class, 'trackOrder']);
Route::get('/app-config', [SettingController::class, 'publicConfig']);

// Protected routes (require auth:sanctum)
Route::group(['middleware' => ['auth:sanctum', UpdateLoginSessionLastSeen::class]], function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::delete('/logout-session/{session}', [AuthController::class, 'logoutSession']);
    Route::get('acl', [AclMatrixController::class, 'matrix']);
    Route::apiResource('expense-categories', ExpenseCategoryController::class);
    Route::apiResource('expenses', ExpenseController::class);
    Route::patch('users/{user}/toggle-block', [UserController::class, 'toggleBlock']);
    Route::patch('users/{user}/roles', [UserController::class, 'updateRoles']);
    Route::patch('clients/{client}/change-plan', [ClientController::class, 'changePlan']);
    Route::apiResource('clients', ClientController::class)->only(['index', 'show']);
    Route::get('profile', [ProfileController::class, 'show']);
    Route::patch('profile', [ProfileController::class, 'update']);
    Route::apiResource('contents', ContentController::class);
    Route::apiResource('shippers', ShipperController::class)->only(['index', 'show']);
    Route::apiResource('users', UserController::class);
    Route::apiResource('roles', RoleController::class);
    Route::apiResource('permissions', PermissionController::class)->only(['index', 'show']);
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::patch('notifications/{notificationId}/read', [NotificationController::class, 'markAsRead']);
    Route::patch('notifications/read-all', [NotificationController::class, 'markAllAsRead']);
    Route::apiResource('refused-reasons', RefusedReasonController::class);
    Route::get('settings', [SettingController::class, 'index']);
    Route::put('settings', [SettingController::class, 'update']);
    Route::get('whatsapp/status', [WhatsAppController::class, 'status']);
    Route::get('whatsapp/qr', [WhatsAppController::class, 'qr']);
    Route::get('whatsapp/groups', [WhatsAppController::class, 'groups']);
    Route::post('whatsapp/restart', [WhatsAppController::class, 'restart']);
    Route::apiResource('governorates', GovernorateController::class);
    Route::apiResource('plans', PlanController::class);
    Route::apiResource('materials', MaterialController::class);
    Route::get('material-requests/init', [MaterialRequestController::class, 'init']);
    Route::apiResource('material-requests', MaterialRequestController::class);
    Route::apiResource('material-request-items', MaterialRequestItemController::class);
    Route::get('pickup-requests/init', [PickupRequestController::class, 'init']);
    Route::apiResource('pickup-requests', PickupRequestController::class);
    Route::apiResource('visits', VisitController::class);
    Route::get('orders/export', [OrderController::class, 'export']);
    Route::post('orders/import', [OrderController::class, 'import']);
    Route::get('orders/import-template', [OrderController::class, 'downloadTemplate']);
    Route::post('orders/scan', [OrderController::class, 'scan']);
    Route::get('orders/my-orders', [OrderController::class, 'myOrders']);
    Route::get('orders/init', [OrderController::class, 'init']);
    Route::patch('orders/bulk-change-status', [OrderController::class, 'bulkChangeStatus']);
    Route::patch('orders/bulk-change-shipper', [OrderController::class, 'bulkChangeShipper']);
    Route::patch('orders/bulk-approve', [OrderController::class, 'bulkApprove']);
    Route::patch('orders/bulk-reject', [OrderController::class, 'bulkReject']);
    Route::delete('orders/bulk-delete', [OrderController::class, 'bulkDestroy']);
    Route::patch('orders/bulk-restore', [OrderController::class, 'bulkRestore']);
    Route::delete('orders/bulk-force-delete', [OrderController::class, 'bulkForceDelete']);
    Route::patch('orders/{order}/change-status', [OrderController::class, 'changeStatus']);
    Route::patch('orders/{order}/change-shipper', [OrderController::class, 'changeShipper']);
    Route::patch('orders/{order}/change-note', [OrderController::class, 'changeNote']);
    Route::patch('orders/{order}/change-external-code', [OrderController::class, 'changeExternalCode']);
    Route::patch('orders/{order}/approve', [OrderController::class, 'approve']);
    Route::patch('orders/{order}/reject', [OrderController::class, 'reject']);
    Route::get('orders/{order}/history', [OrderController::class, 'history']);
    Route::get('orders/{order}/shipping-label', [OrderController::class, 'shippingLabel']);
    Route::get('dashboard/orders', [DashboardOrderController::class, 'summary']);
    Route::patch('orders/{order}/restore', [OrderController::class, 'restore']);
    Route::delete('orders/{order}/force-delete', [OrderController::class, 'forceDelete']);
    Route::apiResource('orders', OrderController::class);
    Route::get('shipper-collections/export', [ShipperCollectionController::class, 'export']);
    Route::get('shipper-collections/eligible-orders', [ShipperCollectionController::class, 'eligibleOrders']);
    Route::patch('shipper-collections/{shipperCollection}/approve', [ShipperCollectionController::class, 'approve']);
    Route::patch('shipper-collections/{shipperCollection}/reject', [ShipperCollectionController::class, 'reject']);
    Route::delete('shipper-collections/{shipperCollection}/orders/{order}', [ShipperCollectionController::class, 'removeOrder']);
    Route::patch('shipper-collections/bulk-status', [ShipperCollectionController::class, 'bulkStatus']);
    Route::apiResource('shipper-collections', ShipperCollectionController::class);

    Route::get('shipper-returns/export', [ShipperReturnController::class, 'export']);
    Route::get('shipper-returns/eligible-orders', [ShipperReturnController::class, 'eligibleOrders']);
    Route::patch('shipper-returns/{shipperReturn}/approve', [ShipperReturnController::class, 'approve']);
    Route::patch('shipper-returns/{shipperReturn}/reject', [ShipperReturnController::class, 'reject']);
    Route::delete('shipper-returns/{shipperReturn}/orders/{order}', [ShipperReturnController::class, 'removeOrder']);
    Route::patch('shipper-returns/bulk-status', [ShipperReturnController::class, 'bulkStatus']);
    Route::post('shipper-returns/bulk-scan', [ShipperReturnController::class, 'bulkScan']);
    Route::apiResource('shipper-returns', ShipperReturnController::class);

    Route::get('client-settlements/export', [ClientSettlementController::class, 'export']);
    Route::get('client-settlements/eligible-orders', [ClientSettlementController::class, 'eligibleOrders']);
    Route::patch('client-settlements/{clientSettlement}/approve', [ClientSettlementController::class, 'approve']);
    Route::patch('client-settlements/{clientSettlement}/reject', [ClientSettlementController::class, 'reject']);
    Route::delete('client-settlements/{clientSettlement}/orders/{order}', [ClientSettlementController::class, 'removeOrder']);
    Route::patch('client-settlements/bulk-status', [ClientSettlementController::class, 'bulkStatus']);
    Route::apiResource('client-settlements', ClientSettlementController::class);

    Route::get('client-returns/export', [ClientReturnController::class, 'export']);
    Route::get('client-returns/eligible-orders', [ClientReturnController::class, 'eligibleOrders']);
    Route::patch('client-returns/{clientReturn}/approve', [ClientReturnController::class, 'approve']);
    Route::patch('client-returns/{clientReturn}/reject', [ClientReturnController::class, 'reject']);
    Route::delete('client-returns/{clientReturn}/orders/{order}', [ClientReturnController::class, 'removeOrder']);
    Route::patch('client-returns/bulk-status', [ClientReturnController::class, 'bulkStatus']);
    Route::post('client-returns/bulk-scan', [ClientReturnController::class, 'bulkScan']);
    Route::apiResource('client-returns', ClientReturnController::class);
    Route::get('activity-logs', [ActivityLogController::class, 'index']);
    Route::get('activity-logs/{activity_log}', [ActivityLogController::class, 'show']);

    // Shipper App API (Dedicated for Representatives)
    Route::group(['prefix' => 'shipper-app', 'middleware' => ['role:super-admin|admin|shipper']], function () {
        Route::get('init', [ShipperAppController::class, 'init']);
        Route::get('orders', [ShipperAppController::class, 'index']);
        Route::get('orders/{order}', [ShipperAppController::class, 'show']);
        Route::patch('orders/{order}/status', [ShipperAppController::class, 'updateStatus']);
        Route::post('scan', [ShipperAppController::class, 'scan']);
        Route::get('stats', [ShipperAppController::class, 'statistics']);
        Route::get('collections', [ShipperAppController::class, 'collections']);
        Route::get('collections/{collection}', [ShipperAppController::class, 'collectionDetails']);
        Route::get('pending-orders', [ShipperAppController::class, 'pendingOrders']);
    });
});
