[program:shipya-whatsapp]
process_name=%(program_name)s
command=/usr/bin/node index.js
directory=/var/www/phpapp/whatsapp-service
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/shipya-whatsapp.log
environment=WHATSAPP_PORT="3001",WHATSAPP_HOST="127.0.0.1"
